name = "omid-hospital"
main = "cloudflare/worker.js"
compatibility_date = "2026-08-24"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "omid-hospital"
database_id = "833af37a-b6b5-4ee1-96fd-825b9bf19c6b"
migrations_dir = "cloudflare/migrations"

[vars]
JWT_EXPIRE_DAYS = "7"
